import { o } from "real-fns";
export declare const template: o.PrefixKeys<{
    "no-mixed-classes": import("@typescript-eslint/utils/dist/ts-eslint/Rule").RuleModule<import("../../../core/base/no-restricted-syntax").MessageId, import("../../../utils/create-rule.internal").PartialOptionsArray<import("../../../core/base/no-restricted-syntax").Options, object, never>, import("@typescript-eslint/utils/dist/ts-eslint/Rule").RuleListener>;
    "no-q-btn": import("@typescript-eslint/utils/dist/ts-eslint/Rule").RuleModule<import("../../../core/base/no-restricted-syntax").MessageId, import("../../../utils/create-rule.internal").PartialOptionsArray<import("../../../core/base/no-restricted-syntax").Options, object, never>, import("@typescript-eslint/utils/dist/ts-eslint/Rule").RuleListener>;
    "no-q-card": import("@typescript-eslint/utils/dist/ts-eslint/Rule").RuleModule<import("../../../core/base/no-restricted-syntax").MessageId, import("../../../utils/create-rule.internal").PartialOptionsArray<import("../../../core/base/no-restricted-syntax").Options, object, never>, import("@typescript-eslint/utils/dist/ts-eslint/Rule").RuleListener>;
    "no-q-card-actions": import("@typescript-eslint/utils/dist/ts-eslint/Rule").RuleModule<import("../../../core/base/no-restricted-syntax").MessageId, import("../../../utils/create-rule.internal").PartialOptionsArray<import("../../../core/base/no-restricted-syntax").Options, object, never>, import("@typescript-eslint/utils/dist/ts-eslint/Rule").RuleListener>;
    "no-q-card-section": import("@typescript-eslint/utils/dist/ts-eslint/Rule").RuleModule<import("../../../core/base/no-restricted-syntax").MessageId, import("../../../utils/create-rule.internal").PartialOptionsArray<import("../../../core/base/no-restricted-syntax").Options, object, never>, import("@typescript-eslint/utils/dist/ts-eslint/Rule").RuleListener>;
    "no-q-expansion-item": import("@typescript-eslint/utils/dist/ts-eslint/Rule").RuleModule<import("../../../core/base/no-restricted-syntax").MessageId, import("../../../utils/create-rule.internal").PartialOptionsArray<import("../../../core/base/no-restricted-syntax").Options, object, never>, import("@typescript-eslint/utils/dist/ts-eslint/Rule").RuleListener>;
    "no-q-field": import("@typescript-eslint/utils/dist/ts-eslint/Rule").RuleModule<import("../../../core/base/no-restricted-syntax").MessageId, import("../../../utils/create-rule.internal").PartialOptionsArray<import("../../../core/base/no-restricted-syntax").Options, object, never>, import("@typescript-eslint/utils/dist/ts-eslint/Rule").RuleListener>;
    "no-q-form": import("@typescript-eslint/utils/dist/ts-eslint/Rule").RuleModule<import("../../../core/base/no-restricted-syntax").MessageId, import("../../../utils/create-rule.internal").PartialOptionsArray<import("../../../core/base/no-restricted-syntax").Options, object, never>, import("@typescript-eslint/utils/dist/ts-eslint/Rule").RuleListener>;
    "no-q-input": import("@typescript-eslint/utils/dist/ts-eslint/Rule").RuleModule<import("../../../core/base/no-restricted-syntax").MessageId, import("../../../utils/create-rule.internal").PartialOptionsArray<import("../../../core/base/no-restricted-syntax").Options, object, never>, import("@typescript-eslint/utils/dist/ts-eslint/Rule").RuleListener>;
    "no-q-item": import("@typescript-eslint/utils/dist/ts-eslint/Rule").RuleModule<import("../../../core/base/no-restricted-syntax").MessageId, import("../../../utils/create-rule.internal").PartialOptionsArray<import("../../../core/base/no-restricted-syntax").Options, object, never>, import("@typescript-eslint/utils/dist/ts-eslint/Rule").RuleListener>;
    "no-q-knob": import("@typescript-eslint/utils/dist/ts-eslint/Rule").RuleModule<import("../../../core/base/no-restricted-syntax").MessageId, import("../../../utils/create-rule.internal").PartialOptionsArray<import("../../../core/base/no-restricted-syntax").Options, object, never>, import("@typescript-eslint/utils/dist/ts-eslint/Rule").RuleListener>;
    "no-q-menu": import("@typescript-eslint/utils/dist/ts-eslint/Rule").RuleModule<import("../../../core/base/no-restricted-syntax").MessageId, import("../../../utils/create-rule.internal").PartialOptionsArray<import("../../../core/base/no-restricted-syntax").Options, object, never>, import("@typescript-eslint/utils/dist/ts-eslint/Rule").RuleListener>;
    "no-q-option-group": import("@typescript-eslint/utils/dist/ts-eslint/Rule").RuleModule<import("../../../core/base/no-restricted-syntax").MessageId, import("../../../utils/create-rule.internal").PartialOptionsArray<import("../../../core/base/no-restricted-syntax").Options, object, never>, import("@typescript-eslint/utils/dist/ts-eslint/Rule").RuleListener>;
    "no-q-popup-proxy": import("@typescript-eslint/utils/dist/ts-eslint/Rule").RuleModule<import("../../../core/base/no-restricted-syntax").MessageId, import("../../../utils/create-rule.internal").PartialOptionsArray<import("../../../core/base/no-restricted-syntax").Options, object, never>, import("@typescript-eslint/utils/dist/ts-eslint/Rule").RuleListener>;
    "no-q-select": import("@typescript-eslint/utils/dist/ts-eslint/Rule").RuleModule<import("../../../core/base/no-restricted-syntax").MessageId, import("../../../utils/create-rule.internal").PartialOptionsArray<import("../../../core/base/no-restricted-syntax").Options, object, never>, import("@typescript-eslint/utils/dist/ts-eslint/Rule").RuleListener>;
    "no-q-toggle": import("@typescript-eslint/utils/dist/ts-eslint/Rule").RuleModule<import("../../../core/base/no-restricted-syntax").MessageId, import("../../../utils/create-rule.internal").PartialOptionsArray<import("../../../core/base/no-restricted-syntax").Options, object, never>, import("@typescript-eslint/utils/dist/ts-eslint/Rule").RuleListener>;
    "no-q-tooltip": import("@typescript-eslint/utils/dist/ts-eslint/Rule").RuleModule<import("../../../core/base/no-restricted-syntax").MessageId, import("../../../utils/create-rule.internal").PartialOptionsArray<import("../../../core/base/no-restricted-syntax").Options, object, never>, import("@typescript-eslint/utils/dist/ts-eslint/Rule").RuleListener>;
    "prefer-label-prop": import("@typescript-eslint/utils/dist/ts-eslint/Rule").RuleModule<import("../../../core/base/no-restricted-syntax").MessageId, import("../../../utils/create-rule.internal").PartialOptionsArray<import("../../../core/base/no-restricted-syntax").Options, object, never>, import("@typescript-eslint/utils/dist/ts-eslint/Rule").RuleListener>;
    "prefer-quasar-components": import("@typescript-eslint/utils/dist/ts-eslint/Rule").RuleModule<import("../../../core/base/no-restricted-syntax").MessageId, import("../../../utils/create-rule.internal").PartialOptionsArray<import("../../../core/base/no-restricted-syntax").Options, object, never>, import("@typescript-eslint/utils/dist/ts-eslint/Rule").RuleListener>;
}, "template/">;
//# sourceMappingURL=index.d.ts.map