import { o } from "real-fns";
export declare const extras: o.PrefixKeys<{
    "check-Props-extends": import("@typescript-eslint/utils/dist/ts-eslint/Rule").RuleModule<import("../../core/base/no-restricted-syntax").MessageId, import("../../utils/create-rule.internal").PartialOptionsArray<import("../../core/base/no-restricted-syntax").Options, object, never>, import("@typescript-eslint/utils/dist/ts-eslint/Rule").RuleListener>;
    "check-Slots-extends": import("@typescript-eslint/utils/dist/ts-eslint/Rule").RuleModule<import("../../core/base/no-restricted-syntax").MessageId, import("../../utils/create-rule.internal").PartialOptionsArray<import("../../core/base/no-restricted-syntax").Options, object, never>, import("@typescript-eslint/utils/dist/ts-eslint/Rule").RuleListener>;
    "consistent-optional-props": import("@typescript-eslint/utils/dist/ts-eslint/Rule").RuleModule<import("../../core/base/consistent-optional-props").MessageId, import("../../utils/create-rule.internal").PartialOptionsArray<import("../../core/base/consistent-optional-props").Options, import("../../core/base/consistent-optional-props").Suboptions, "overrides">, import("@typescript-eslint/utils/dist/ts-eslint/Rule").RuleListener>;
    "no-OwnProps-extends": import("@typescript-eslint/utils/dist/ts-eslint/Rule").RuleModule<import("../../core/base/no-restricted-syntax").MessageId, import("../../utils/create-rule.internal").PartialOptionsArray<import("../../core/base/no-restricted-syntax").Options, object, never>, import("@typescript-eslint/utils/dist/ts-eslint/Rule").RuleListener>;
    "no-OwnSlots-extends": import("@typescript-eslint/utils/dist/ts-eslint/Rule").RuleModule<import("../../core/base/no-restricted-syntax").MessageId, import("../../utils/create-rule.internal").PartialOptionsArray<import("../../core/base/no-restricted-syntax").Options, object, never>, import("@typescript-eslint/utils/dist/ts-eslint/Rule").RuleListener>;
    "no-empty-interfaces": import("@typescript-eslint/utils/dist/ts-eslint/Rule").RuleModule<import("../../core/base/no-restricted-syntax").MessageId, import("../../utils/create-rule.internal").PartialOptionsArray<import("../../core/base/no-restricted-syntax").Options, object, never>, import("@typescript-eslint/utils/dist/ts-eslint/Rule").RuleListener>;
    "prefer-OwnProps": import("@typescript-eslint/utils/dist/ts-eslint/Rule").RuleModule<import("../../core/base/no-restricted-syntax").MessageId, import("../../utils/create-rule.internal").PartialOptionsArray<import("../../core/base/no-restricted-syntax").Options, object, never>, import("@typescript-eslint/utils/dist/ts-eslint/Rule").RuleListener>;
    "prefer-OwnSlots": import("@typescript-eslint/utils/dist/ts-eslint/Rule").RuleModule<import("../../core/base/no-restricted-syntax").MessageId, import("../../utils/create-rule.internal").PartialOptionsArray<import("../../core/base/no-restricted-syntax").Options, object, never>, import("@typescript-eslint/utils/dist/ts-eslint/Rule").RuleListener>;
}, "extras/">;
//# sourceMappingURL=index.d.ts.map