import { o } from "real-fns";
export declare const vue: o.PrefixKeys<{
    "component-name": import("@typescript-eslint/utils/dist/ts-eslint/Rule").RuleModule<import("../core/base/match-filename").MessageId, import("../utils/create-rule.internal").PartialOptionsArray<import("../core/base/match-filename").Options, object, never>, import("@typescript-eslint/utils/dist/ts-eslint/Rule").RuleListener>;
    "no-complex-declarator-type": import("@typescript-eslint/utils/dist/ts-eslint/Rule").RuleModule<import("../typescript/base/no-restricted-syntax").MessageId, import("../utils/create-rule.internal").PartialOptionsArray<import("../typescript/base/no-restricted-syntax").Options, object, never>, import("@typescript-eslint/utils/dist/ts-eslint/Rule").RuleListener>;
    "no-complex-return-type": import("@typescript-eslint/utils/dist/ts-eslint/Rule").RuleModule<import("../typescript/base/no-restricted-syntax").MessageId, import("../utils/create-rule.internal").PartialOptionsArray<import("../typescript/base/no-restricted-syntax").Options, object, never>, import("@typescript-eslint/utils/dist/ts-eslint/Rule").RuleListener>;
    "element-contents-spacing": import("@typescript-eslint/utils/dist/ts-eslint/Rule").RuleModule<import("./base/element-contents-spacing").MessageId, import("../utils/create-rule.internal").PartialOptionsArray<object, object, never>, import("@typescript-eslint/utils/dist/ts-eslint/Rule").RuleListener>;
    "no-readonly-v-model": import("@typescript-eslint/utils/dist/ts-eslint/Rule").RuleModule<import("./base/no-readonly-v-model").MessageId, import("../utils/create-rule.internal").PartialOptionsArray<object, object, never>, import("@typescript-eslint/utils/dist/ts-eslint/Rule").RuleListener>;
    "sort-v-bind": import("@typescript-eslint/utils/dist/ts-eslint/Rule").RuleModule<import("./base/sort-v-bind").MessageId, import("../utils/create-rule.internal").PartialOptionsArray<object, object, never>, import("@typescript-eslint/utils/dist/ts-eslint/Rule").RuleListener>;
}, "vue/">;
//# sourceMappingURL=index.d.ts.map