name: scan-with-sonar
on:
  push:
    branches:
      - master
      - develop
  workflow_dispatch:
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Use checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Scan with sonar
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
